// Code generated by Kitex v0.7.2. DO NOT EDIT.

package onlineservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	online "github.com/li1553770945/sheepim-online-service/kitex_gen/online"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SetClientStatus(ctx context.Context, req *online.SetClientStatusReq, callOptions ...callopt.Option) (r *online.SetClientStatusResp, err error)
	GetOnlineMemberEndpoint(ctx context.Context, req *online.GetOnlineMemberEndpointReq, callOptions ...callopt.Option) (r *online.GetOnlineMemberEndpointResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOnlineServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOnlineServiceClient struct {
	*kClient
}

func (p *kOnlineServiceClient) SetClientStatus(ctx context.Context, req *online.SetClientStatusReq, callOptions ...callopt.Option) (r *online.SetClientStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetClientStatus(ctx, req)
}

func (p *kOnlineServiceClient) GetOnlineMemberEndpoint(ctx context.Context, req *online.GetOnlineMemberEndpointReq, callOptions ...callopt.Option) (r *online.GetOnlineMemberEndpointResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOnlineMemberEndpoint(ctx, req)
}
